### ISSUE TITLE
tidy_strong_params is not Ruby 3.x compatible

### ISSUE THREAD

**Issue by pkmuldoon** [yak-shak/tidy_strong_params#11]
Just leaving a note that this gem is not Ruby 3.x compatible. Can you please either fix up the gem to work with Ruby 3.x or restrict the gem spec to < 3.x? If I get time this weekend, I'll have a stab at updating it:

```rspec
tidy_strong_params on 🌱 master [?] via 💎 v3.0.2 took 7s
➜ bundle exec rspec spec/

TidyStrongParams::Controller
  controller without existing params method
    sets params method
    sets loads param method from Gem
  controller with existing params method
    skips setting params method
    keeps the classes original method
  #tidy_params_scope
    returns the set scope
    returns nil if scope not set

TidyStrongParams::Resource
  returns a name
  params_class_name correct string
  with a nested module
    returns a non-nested name
  #strong_params_class
    resource with a params class
      returns a strong_params_class
    resource without params class
      raises params class not defined error

TidyStrongParams::StrongParams
  allows listed params (FAILED - 1)
  rejects non listed params (FAILED - 2)
  supports arrays (FAILED - 3)
  supports nested params (FAILED - 4)
  #required
    required param present
      works (FAILED - 5)
    required param missing
      raises error (FAILED - 6)
    required param set to false
      doesn't enforce a required param (FAILED - 7)
  #tap_params
    includes tap_params methods modifications (FAILED - 8)
  #params
    allows params method to be overridden (FAILED - 9)
  #scope
    scope not defined
      throws an error (FAILED - 10)
    scope defined
      utilizes the set scope (FAILED - 11)
      includes the scope dependant attribute (FAILED - 12)

TidyStrongParams
  has a version number
  passes smoke test (FAILED - 13)

Failures:

  1) TidyStrongParams::StrongParams allows listed params
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:16:in `block (2 levels) in <top (required)>'

  2) TidyStrongParams::StrongParams rejects non listed params
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:21:in `block (2 levels) in <top (required)>'

  3) TidyStrongParams::StrongParams supports arrays
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:25:in `block (2 levels) in <top (required)>'

  4) TidyStrongParams::StrongParams supports nested params
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:29:in `block (2 levels) in <top (required)>'

  5) TidyStrongParams::StrongParams#required required param present works
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:35:in `block (3 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:40:in `block (4 levels) in <top (required)>'

  6) TidyStrongParams::StrongParams#required required param missing raises error
     Failure/Error: expect{ subject }.to raise_exception(ActionController::ParameterMissing)

       expected ActionController::ParameterMissing, got #<ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: raw_params)> with backtrace:
         # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
         # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
         # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
         # ./spec/strong_params_spec.rb:35:in `block (3 levels) in <top (required)>'
         # ./spec/strong_params_spec.rb:47:in `block (5 levels) in <top (required)>'
         # ./spec/strong_params_spec.rb:47:in `block (4 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:47:in `block (4 levels) in <top (required)>'

  7) TidyStrongParams::StrongParams#required required param set to false doesn't enforce a required param
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:52:in `block (4 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:56:in `block (4 levels) in <top (required)>'

  8) TidyStrongParams::StrongParams#tap_params includes tap_params methods modifications
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:62:in `block (3 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:65:in `block (3 levels) in <top (required)>'

  9) TidyStrongParams::StrongParams#params allows params method to be overridden
     Failure/Error:
       def initialize(raw_params:, resource_name: '', scope: nil)
         self.raw_params = raw_params
         self.resource_name = resource_name
         self.scope = scope
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0; required keyword: raw_params)
     # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
     # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
     # ./spec/strong_params_spec.rb:70:in `block (3 levels) in <top (required)>'
     # ./spec/strong_params_spec.rb:73:in `block (3 levels) in <top (required)>'

  10) TidyStrongParams::StrongParams#scope scope not defined throws an error
      Failure/Error: expect{ subject }.to raise_exception(NoMethodError)

        expected NoMethodError, got #<ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: raw_params)> with backtrace:
          # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
          # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
          # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
          # ./spec/strong_params_spec.rb:80:in `block (3 levels) in <top (required)>'
          # ./spec/strong_params_spec.rb:86:in `block (5 levels) in <top (required)>'
          # ./spec/strong_params_spec.rb:86:in `block (4 levels) in <top (required)>'
      # ./spec/strong_params_spec.rb:86:in `block (4 levels) in <top (required)>'

  11) TidyStrongParams::StrongParams#scope scope defined utilizes the set scope
      Failure/Error: expect{subject}.to_not raise_exception

        expected no Exception, got #<ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: raw_params)> with backtrace:
          # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
          # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
          # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
          # ./spec/strong_params_spec.rb:80:in `block (3 levels) in <top (required)>'
          # ./spec/strong_params_spec.rb:94:in `block (5 levels) in <top (required)>'
          # ./spec/strong_params_spec.rb:94:in `block (4 levels) in <top (required)>'
      # ./spec/strong_params_spec.rb:94:in `block (4 levels) in <top (required)>'

  12) TidyStrongParams::StrongParams#scope scope defined includes the scope dependant attribute
      Failure/Error:
        def initialize(raw_params:, resource_name: '', scope: nil)
          self.raw_params = raw_params
          self.resource_name = resource_name
          self.scope = scope
        end

      ArgumentError:
        wrong number of arguments (given 1, expected 0; required keyword: raw_params)
      # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
      # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
      # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
      # ./spec/strong_params_spec.rb:80:in `block (3 levels) in <top (required)>'
      # ./spec/strong_params_spec.rb:98:in `block (4 levels) in <top (required)>'

  13) TidyStrongParams passes smoke test
      Failure/Error:
        def initialize(raw_params:, resource_name: '', scope: nil)
          self.raw_params = raw_params
          self.resource_name = resource_name
          self.scope = scope
        end

      ArgumentError:
        wrong number of arguments (given 1, expected 0; required keyword: raw_params)
      # ./lib/tidy_strong_params/strong_params.rb:10:in `initialize'
      # ./lib/tidy_strong_params/strong_params.rb:17:in `new'
      # ./lib/tidy_strong_params/strong_params.rb:17:in `restrict'
      # ./lib/tidy_strong_params/controller.rb:24:in `block in <module:Controller>'
      # ./spec/tidy_strong_params_spec.rb:23:in `block (2 levels) in <top (required)>'

Finished in 0.01578 seconds (files took 0.75823 seconds to load)
25 examples, 13 failures

Failed examples:
```

**Comment by pkmuldoon** [comment]
I've created a PR from the fork I made: https://github.com/yak-shak/tidy_strong_params/pull/12
